### ISSUE TITLE
Zrobione

### ISSUE THREAD

**Issue by JoannaKu** [JoannaKu/Java-Script#2]
O to chodziło?

**Comment by michal-bootcamp** [comment]
Tak, o to chodzilo. Komentarze mozesz dodawac w tym samym issue.
Usunalem jeszcze niepotrzebny komentarz w html i poprawilem wciecia. Zmiany mozesz sobie zaciagnac do siebie lokalnie za pomoca `git pull`, a do podejrzenia tutaj: https://github.com/JoannaKu/Java-Script/commit/dda0605ba8a513589040e8b121db92cf7467e057
